apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  # - host: foo.bar.com
  - http:
    paths:
    - path: /
      backend:
        serviceName: helm/hooks/frontends
        servicePort: 80
    # - path: /bar
    #   backend:
    #     serviceName: svc2
    #     servicePort: 80